### ISSUE TITLE
Measurement numbers of hypotenuse intersect in dark mode

### ISSUE THREAD

**Issue by adamp4** [Bluegrams/ScreenRuler#49]
<img width="302" alt="批注 2021-11-07 160338" src="https://user-images.githubusercontent.com/44283910/140637291-a4ed7bfb-5eb2-48e8-a4f5-1268c97f43f2.png">

**Comment by adamp4** [comment]
Hard to read mesurement numbers of heigh
<img width="157" alt="批注 2021-11-07 173352" src="https://user-images.githubusercontent.com/44283910/140639901-9383039a-3d5f-44aa-8046-0b16e4cdf6a5.png">
t

**Comment by alxnull** [comment]
Hey @adamp4, unfortunately, I'm currently unable to reproduce these issues with the latest version (0.9.1) of ScreenRuler. Could you add some details about your setup, e.g. are you using high-DPI monitors, Windows display scaling, and/multiple monitors with different resolutions?

**Comment by adamp4** [comment]
Hi @alxnull, Yes i'm using high DPI monitor, no mutiple monitors, i'v set high DPI scalling override property as 'application'.
<img width="422" alt="批注 2022-04-07 214708" src="https://user-images.githubusercontent.com/44283910/162214054-550349cf-253c-435b-b087-31ec1c2cb3fc.png">

![Uploading image.png…]()
<img width="458" alt="批注 2022-04-07 214910" src="https://user-images.githubusercontent.com/44283910/162214710-6962fc15-bf50-4ff9-8967-0e1972668c2d.png">

**Comment by adamp4** [comment]
Hi @alxnull, Yes i'm using high DPI monitor, no mutiple monitors, i'v set high DPI scalling override property as 'application'.
<img width="422" alt="批注 2022-04-07 214708" src="https://user-images.githubusercontent.com/44283910/162214054-550349cf-253c-435b-b087-31ec1c2cb3fc.png">

![Uploading image.png…]()
<img width="458" alt="批注 2022-04-07 214910" src="https://user-images.githubusercontent.com/44283910/162214710-6962fc15-bf50-4ff9-8967-0e1972668c2d.png">

**Comment by alxnull** [comment]
@adamp4 I believe this issue is related to the display scaling issues described in #52. I'm currently testing an update that should fix these kinds of problems there. Would be happy if you could try out the preview version from https://github.com/Bluegrams/ScreenRuler/issues/52#issue-1118361298 and give feedback there if this fixes your issue. Thanks!

**Comment by adamp4** [comment]
@alxnull Tried, issue still exists.

![image](https://user-images.githubusercontent.com/44283910/162720749-1626b0e6-3eee-4b40-bec8-3de5a6aa2b1b.png)

**Comment by adamp4** [comment]
@alxnull The height of rows shrink when applied high DPI scalling override property
<img width="376" alt="批注 2022-04-11 182740" src="https://user-images.githubusercontent.com/44283910/162721759-db048c46-089f-40e7-a019-cca63981bf4c.png">

**Comment by alxnull** [comment]
Took a look at the two specific problems again and made another fix. Download still at https://sourceforge.net/projects/screenruler/files/pre-release/ScreenRuler-v.0.10.0-Portable.zip/download. Please try again, thanks!

**Comment by adamp4** [comment]
@alxnull Fixed, one more step to be prefect, pls check attached pic.
<img width="395" alt="批注 2022-04-12 141326" src="https://user-images.githubusercontent.com/44283910/162893447-6d3c147a-a608-4ea7-9bcf-f52ced4dfd5b.png">

**Comment by adamp4** [comment]
@alxnull Chinese(PRC) translation suggestion for "keyboard shorts" : 热键设置 
<img width="248" alt="批注 2022-04-12 142126" src="https://user-images.githubusercontent.com/44283910/162894095-ef471a6a-7851-4bfe-89df-cee0cc15045a.png">

**Comment by adamp4** [comment]
@alxnull I modified Help.zh-CN.html for better readability. Pls check attachment
[Help.zh.html.zip](https://github.com/Bluegrams/ScreenRuler/files/8470118/Help.zh.html.zip)

**Comment by adamp4** [comment]
@alxnull
<img width="412" alt="批注 2022-04-12 143350" src="https://user-images.githubusercontent.com/44283910/162895909-12b7d156-247f-4564-99e6-791186d8dfd2.png">

**Comment by adamp4** [comment]
@alxnull
<img width="370" alt="批注 2022-04-12 143711" src="https://user-images.githubusercontent.com/44283910/162896330-9216fde3-a455-4234-8f14-e42a6a2b1b7e.png">

**Comment by adamp4** [comment]
@alxnull The ruler scale is not slim after applied 'slim scale', just personal option, the pervious slim mode is much better.
![未命名](https://user-images.githubusercontent.com/44283910/162899749-652a67bd-4683-4d12-ab47-fef476e356b8.png)

**Comment by adamp4** [comment]
@alxnull App crashed when i open marker list and closed then right click ruler to open menu.
<img width="416" alt="批注 2022-04-12 150626" src="https://user-images.githubusercontent.com/44283910/162900984-60b7e505-32a5-482e-a08b-430249289cb6.png">

************** 异常文本 **************
System.ObjectDisposedException: 无法访问已释放的对象。
对象名:“MarkerListForm”。
   在 System.Windows.Forms.Control.CreateHandle()
   在 System.Windows.Forms.Form.CreateHandle()
   在 System.Windows.Forms.Control.get_Handle()
   在 ScreenRuler.Units.UnitConverter.FromSettings(Control control, Settings settings, Nullable`1 unit)
   在 ScreenRuler.MarkerListForm.updateUnitConverter(Nullable`1 unit)
   在 ScreenRuler.MarkerListForm.settings_Changed(Object sender, EventArgs e)
   在 ScreenRuler.Configuration.Settings.InvokeChanged()
   在 ScreenRuler.RulerForm.comUnits_SelectedIndexChanged(Object sender, EventArgs e)
   在 System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   在 System.Windows.Forms.ToolStripComboBox.OnSelectedIndexChanged(EventArgs e)
   在 System.Windows.Forms.ToolStripComboBox.HandleSelectedIndexChanged(Object sender, EventArgs e)
   在 System.Windows.Forms.ComboBox.OnSelectedIndexChanged(EventArgs e)
   在 System.Windows.Forms.ComboBox.set_SelectedIndex(Int32 value)
   在 System.Windows.Forms.ToolStripComboBox.set_SelectedIndex(Int32 value)
   在 ScreenRuler.RulerForm.contxtMenu_Opening(Object sender, CancelEventArgs e)
   在 System.Windows.Forms.ToolStripDropDown.OnOpening(CancelEventArgs e)
   在 System.Windows.Forms.ToolStripDropDown.SetVisibleCore(Boolean visible)
   在 System.Windows.Forms.ContextMenuStrip.SetVisibleCore(Boolean visible)
   在 System.Windows.Forms.ToolStripDropDown.Show(Control control, Point position)
   在 System.Windows.Forms.ContextMenuStrip.ShowInternal(Control source, Point location, Boolean isKeyboardActivated)
   在 System.Windows.Forms.Control.WmContextMenu(Message& m, Control sourceControl)
   在 System.Windows.Forms.Control.WmContextMenu(Message& m)
   在 System.Windows.Forms.Control.WndProc(Message& m)
   在 System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   在 System.Windows.Forms.ContainerControl.WndProc(Message& m)
   在 System.Windows.Forms.Form.WndProc(Message& m)
   在 ScreenRuler.RulerForm.WndProc(Message& m)
   在 System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   在 System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** 已加载的程序集 **************
mscorlib
    程序集版本:4.0.0.0
    Win32 版本:4.8.4250.0 built by: NET48REL1LAST_C
    基本代码:file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
screenruler
    程序集版本:0.10.0.0
    Win32 版本:0.10.0
    基本代码:file:///D:/Pro/ScreenRuler/screenruler.exe
----------------------------------------
System
    程序集版本:4.0.0.0
    Win32 版本:4.8.4200.0 built by: NET48REL1LAST_C
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
CommandLine
    程序集版本:2.8.0.0
    Win32 版本:0.10.0
    基本代码:file:///D:/Pro/ScreenRuler/screenruler.exe
----------------------------------------
System.Core
    程序集版本:4.0.0.0
    Win32 版本:4.8.4220.0 built by: NET48REL1LAST_C
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Windows.Forms
    程序集版本:4.0.0.0
    Win32 版本:4.8.4250.0 built by: NET48REL1LAST_C
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    程序集版本:4.0.0.0
    Win32 版本:4.8.4084.0 built by: NET48REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
AppHelpers.WinForms
    程序集版本:0.1.1.0
    Win32 版本:0.10.0
    基本代码:file:///D:/Pro/ScreenRuler/screenruler.exe
----------------------------------------
System.Configuration
    程序集版本:4.0.0.0
    Win32 版本:4.8.4190.0 built by: NET48REL1LAST_B
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    程序集版本:4.0.0.0
    Win32 版本:4.8.4084.0 built by: NET48REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
PortableSettingsProvider
    程序集版本:0.2.4.0
    Win32 版本:0.10.0
    基本代码:file:///D:/Pro/ScreenRuler/screenruler.exe
----------------------------------------
System.Xml.Linq
    程序集版本:4.0.0.0
    Win32 版本:4.8.4084.0 built by: NET48REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    程序集版本:0.0.0.0
    Win32 版本:4.8.4250.0 built by: NET48REL1LAST_C
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_32/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
screenruler.resources
    程序集版本:0.10.0.0
    Win32 版本:0.10.0
    基本代码:file:///D:/Pro/ScreenRuler/zh-CN/screenruler.resources.DLL
----------------------------------------
System.Windows.Forms.resources
    程序集版本:4.0.0.0
    Win32 版本:4.8.4084.0 built by: NET48REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------
Accessibility
    程序集版本:4.0.0.0
    Win32 版本:4.8.4084.0 built by: NET48REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
Microsoft.GeneratedCode
    程序集版本:1.0.0.0
    Win32 版本:4.8.4084.0 built by: NET48REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.xml.resources
    程序集版本:4.0.0.0
    Win32 版本:4.8.4084.0 built by: NET48REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/System.Xml.resources.dll
----------------------------------------
Microsoft.GeneratedCode
    程序集版本:1.0.0.0
    Win32 版本:4.8.4084.0 built by: NET48REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    程序集版本:1.0.0.0
    Win32 版本:4.8.4084.0 built by: NET48REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
mscorlib.resources
    程序集版本:4.0.0.0
    Win32 版本:4.8.4084.0 built by: NET48REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
Microsoft.GeneratedCode
    程序集版本:1.0.0.0
    Win32 版本:4.8.4084.0 built by: NET48REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.resources
    程序集版本:4.0.0.0
    Win32 版本:4.8.4084.0 built by: NET48REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/System.resources.dll
----------------------------------------
Bluegrams.Windows.Tools
    程序集版本:0.1.0.0
    Win32 版本:0.10.0
    基本代码:file:///D:/Pro/ScreenRuler/screenruler.exe
----------------------------------------

************** JIT 调试 **************
要启用实时(JIT)调试，
该应用程序或计算机的 .config 文件(machine.config)的 system.windows.forms 节中必须设置
jitDebugging 值。
编译应用程序时还必须启用
调试。

例如:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

启用 JIT 调试后，任何未经处理的异常
都将被发送到在此计算机上注册的 JIT 调试程序，
而不是由此对话框处理。

**Comment by alxnull** [comment]
@adamp4 Thanks for bringing up all these issues, this helps a lot with the development! I tried to fix most of what you mentioned and uploaded a new preview (again same link). Regarding some of your notes:

> @alxnull Fixed, one more step to be prefect, pls check attached pic.

While this overlapping does not look great, it is somewhat expected in this case. You can always disable the length labels via `Appearance -> Show Offset and Length` in the context menu.

The cut-off label box in the picture with the hypotenuse is difficult to fully fix as the app is unable to draw on the screen beyond the length of the vertical ruler scale currently. I tried to improve it a bit, but the box might still be cut off.

> @alxnull The ruler scale is not slim after applied 'slim scale', just personal option, the pervious slim mode is much better.

I believe this is expected with the new scaling of the UI.

Please let me know if anything else is not working as expected, thanks!

**Comment by adamp4** [comment]
@alxnull It's my pleasure helped you developing such good tool. Pls chek issues i figured below.
1..Default colume width of 'keyboard shortcuts' could be extended.
<img width="259" alt="2022-04-14 083139" src="https://user-images.githubusercontent.com/44283910/163294249-6f0dfafc-fbd5-42be-a448-15f9b409d276.png">

2.Default setting 'always on top' not working, it works after cancel and select this option again.
3.Esc can't close markers list box, keyboard shorcuts box and help box (it works for menu, set ruler size box, settings, calibrate ruler box, about box)
4.The cpu usage keeps roughly 17%, may it be possible to be reduced when not resizing?

**Comment by alxnull** [comment]
@adamp4 Points 1 & 3 should be fixed now.

> 2.Default setting 'always on top' not working, it works after cancel and select this option again.

Unfortunately, I'm unable to reproduce this issue on my side. Not sure what the cause for this could be.

> 4.The cpu usage keeps roughly 17%, may it be possible to be reduced when not resizing?

That seems to be quite a lot. Is the CPU usage this high even if you don't actively interact with the ruler?

**Comment by adamp4** [comment]
@alxnull The CPU usage depends on the size of ruler, in my case the ruler size was 2160px*1274px.
<img width="1070" alt="批注 2022-04-16 185335" src="https://user-images.githubusercontent.com/44283910/163672295-689dc55c-00fa-4e5f-96bf-edb86b035a67.png">
<img width="1076" alt="批注 2022-04-16 185618" src="https://user-images.githubusercontent.com/44283910/163672349-f18bbe2c-cb98-4c96-b0be-e28dc92065db.png">

**Comment by alxnull** [comment]
Most of the fixes of the described issues are now released in v.0.10.0 of ScreenRuler: http://bluegrams.com/blog/2022/09/screen-ruler-0-10-with-improved-scaling-calibration-and-configuration.html
